[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blockchain_logic_stablefunds = "AT9tsBfMFcNuTAfxTFnUZ54hKdcTuPvYPgSyb1rzQJ8G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id-NCN-AVS.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
