[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablefunds_program = "97XJBATGaXqBSVRQYszL7pr4RP46Uv9KH6FzcLx3zgd8"

[programs.testnet]
stablefunds_program = "97XJBATGaXqBSVRQYszL7pr4RP46Uv9KH6FzcLx3zgd8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
generate-idl = "anchor build && cp target/idl/stablefunds_program.json ../frontend/src/services/anchor-client/idl.json"
