[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
stablefunds = "36Pd9Lzj64MpvJyw5kNyv54xqddeYc1fanat5zrTyWpn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
